image:
  name: "microservice-8-savedetails"
  tag: latest
  restartPolicy: Always

service:
  type: ClusterIP
  port: 80
  name: microservice-8-savedetails

environment:
  name: "default"
  replicas:
    quantity: 1
  resources:
    xmx: 700M
    xms: 200M  
